version: '3.8'

services:
  integration-service:
    container_name: integration-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    env_file:
      - .env
    depends_on:
      postgres_db:
          condition: service_healthy
      redis_cache:
          condition: service_started
    networks:
      - llt-net

  postgres_db:
    image: postgres:15-alpine
    container_name: integration-postgres
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - llt-net

  redis_cache:
    image: redis:7-alpine
    container_name: llt-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - llt-net

networks:
  llt-net:
    external: true
    name: llt-net

volumes:
  pg_data:
  redis_data:
